name: spacexplorer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  # API_COM is my own wrapper around http package. 
  # Currently is in the development stage but it already works even though the code is not perfect and it was successfully used in a production environment.
  api_com: 
    git:
      url: https://github.com/CreevekCZ/api_com
      ref: devel
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  go_router: ^6.5.2
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.2
  intl: ^0.17.0
  json_annotation: ^4.8.0
  palestine_console: ^0.0.10
  unfocus_widget: ^0.0.4
  uuid: ^3.0.7

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6




flutter:
  uses-material-design: true
  # assets:
  #   - assets/
