name: spacexplorer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.2
  http: ^0.13.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  palestine_console: ^0.0.10

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  json_serializable: ^6.6.2
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
